services:
  db:
    image: postgres:15-alpine
    container_name: time_tracker_db
    environment:
      POSTGRES_MULTIPLE_DATABASES: jira_db,app_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  jira:
    image: atlassian/jira-software:latest
    container_name: jira_local
    ports:
      - "8081:8080"
    environment:
      - ATL_JDBC_USER=dev_user
      - ATL_JDBC_PASSWORD=dev_password
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jira_db
      - ATL_DB_TYPE=postgres72
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=2500m
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 3G   